export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const EMPLOYEES_SUCCESS = 'EMPLOYEES_SUCCESS';
export const EMPLOYEES_FAILURE = 'EMPLOYEES_FAILURE';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';

export const EMPLOYEE_FIND_SUCCESS =  "EMPLOYEE_FIND_SUCCESS"

// export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
// export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
// export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';
// export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
